# @name get-prompts
GET http://localhost:4403/prompts

###

# @name upload
POST http://localhost:4403/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="teste.mp3"
Content-Type: audio/mpeg;

< ./teste.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:4403/videos/154d3756-f989-4606-9454-bea7ebb1a434/transcription
Content-Type: application/json

{
    "prompt": "mp3, test, upload"
}

###

# @name generate-ai-completion
POST http://localhost:4403/ai/complete
Content-Type: application/json

{
    "videoId": "154d3756-f989-4606-9454-bea7ebb1a434",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}